### ISSUE TITLE
Enhancement request: Key out the background for the iframes at the bottom

### ISSUE THREAD

**Issue by asdf1234-deleted** [mocdaniel/dashing-icinga2#103]
I'm sure you thought about this before, but not sure what is doable here to have a consistent theme:

![image](https://user-images.githubusercontent.com/27829577/75991092-ee6d5e00-5ec3-11ea-80ba-8913df413151.png)

It would be nice to key out the white here, but I suppose that depends on Icingaweb2 really.

**Comment by mocdaniel** [comment]
This is not possible via dashing-icinga, as it's just an iFrame showing the actual icingaweb2 landing page. You would have to configure a fitting icingaweb2 theme, but with a transparent background, nobody could see the actual content in icingaweb2, I'm afraid.

**Comment by dnsmichi** [comment]
Indeed, thanks @mocdaniel
