### ISSUE TITLE
Object not found! Error in Last two panel

### ISSUE THREAD

**Issue by naveenlr92** [mocdaniel/dashing-icinga2#104]
Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404
localhost
03/14/20 12:57:37
Apache/2.2.21 (Win32) mod_ssl/2.2.21 OpenSSL/1.0.0e PHP/5.3.8 mod_perl/2.0.4 Perl/v5.10.1

**Comment by mocdaniel** [comment]
The last two frames show your configured icingaweb2 instance via iFrames. For this to work you need to enter the right url in your `./config/icinga2.json` or `./config/icinga2.local.json`. Sometimes you also need to adjust the iFrame-settings on the webserver hosting your icingaweb2-instance. For this you would need to contact your webadministrator.

**Comment by naveenlr92** [comment]
Where I can found the iFrame-settings ????

**Comment by mocdaniel** [comment]
As I told you in my last post already, this depends heavily on the way you configured Icingaweb2 on your web host. If you followed the Icingaweb2 installation documentation, you probably used Apache2. Then you would have to add the directive 

`Header set X-Frame-Options ALLOW-FROM https://<ip-address or domain of dashing-icinga>` 

to the relevant config files handling and serving your icingaweb2 instance. As I said, talking to your web admin about this matter will probably be more valuable than opening an issue (which it probably isn't, at least not with dashing-icinga) here.

**Comment by naveenlr92** [comment]
That's fine now I found the solution thanks for this,

**Comment by naveenlr92** [comment]
One more Icinga dashing site can’t provide a secure connection cannot make a SSL connection

**Comment by mocdaniel** [comment]
This is once again up to your configuration. Due to dashing-icinga running its own `thin`-webserver on port `8005` per default, you would most likely want to establish an SSL-connection port 443 of your system and redirect/reverse-proxy to port 8005 then. Once again: **please ask your web admin about these issues.** I am closing here for now.

**Comment by naveenlr92** [comment]
that's steps has finished again facing the same issue
https://community.icinga.com/t/shared-web-server-for-dashing-icinga2-and-icingaweb2/330

I'm Try to install the new package my own
