### ISSUE TITLE
cookies problem on CHROME

### ISSUE THREAD

**Issue by picoroma** [mocdaniel/dashing-icinga2#106]
dashing (1.3.7)
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.3-1)
<!-- Formatting tips:
Hi!
I have installed dashing  on a standalone server. 
I run with service,
I have problem with the iFrame (Web HOST Problem and Web Service Problem)
"Cookies must be enabled to run this application."
On CHROME Browser do not work and is not possible to login on icinga2.
I hace also enable cookies for host but nothing change.
on Firefor I have no problem and the icinga2 login page appear.

**Comment by mocdaniel** [comment]
What do you mean by "cookies problem"? The login status in the two icingaweb iFrames?

**Comment by picoroma** [comment]
Yes,Do not appear on chrome.Appear correctly on Firefox.P.Il 22 mar 2020 18:52, Daniel <notifications@github.com> ha scritto:
What do you mean by "cookies problem"? The login status in the two icingaweb iFrames?

**Comment by mocdaniel** [comment]
With so little information all I could find is this:

https://stackoverflow.com/a/18223158/6703854

Could you provide a screenshot of your dashboard, the exact entry of your icinga2.local.conf or icinga2.conf for dashing-icinga and tell me if your icingaweb2 is accessible via https or http only?

**Comment by picoroma** [comment]
My icingaweb2 is accessible only in HTTP 

Dashboard is attached. And cookies as enabled as tou can see on
top-right. 

The config file - icinga2.local.conf- looks like: 

{
"icinga2": {
"api": {
"host": "icinga2-prd.bgp.locale",
"port": 5665,
"user": "root",
"password": "my-root-pswd"
}
},
"icingaweb2": {
"url": "http://icinga2-prd.bgp.locale/icingaweb2"
},
"dashboard": {
"show_only_hard_state_problems": false,
"timezone": "Europe/Rome"
}
} 

Il 22-03-2020 19:16 Daniel ha scritto:

> With so little information all I could find is this: 
> 
> https://stackoverflow.com/a/18223158/6703854 
> 
> Could you provide a screenshot of your dashboard, the exact entry of your icinga2.local.conf or icinga2.conf for dashing-icinga and tell me if your icingaweb2 is accessible via https or http only? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/dnsmichi/dashing-icinga2/issues/106#issuecomment-602249983
[2]

**Comment by mocdaniel** [comment]
The configuration looks fine. Since the same dashing-icinga version is running fine with Chrome for me both from work as well as from home, you might want to look around the internet regarding solutions for this problem as it might be caused server-sided by the webserver which is hosting your icingaweb2. Do the logs of dashing or your icingaweb2-webserver show any strange outputs?

**Comment by picoroma** [comment]
The problem seems to be related to Chrome.With FF I have a normal beheavior....Il 22 mar 2020 20:50, Daniel <notifications@github.com> ha scritto:
The configuration looks fine. Since the same dashing-icinga version is running fine with Chrome for me both from work as well as from home, you might want to look around the internet regarding solutions for this problem as it might be caused server-sided by the webserver which is hosting your icingaweb2. Do the logs of dashing or your icingaweb2-webserver show any strange outputs?

**Comment by dnsmichi** [comment]
@picoroma Please use the web form for comments, or fix your mail client replies to allow better formatting. 

Other than that, I suspect that you should look into the icingaweb2 project, where the cookie might need to be stored. The dev console might shed some light as well, and maybe you've hit a web2 bug.

**Comment by picoroma** [comment]
Hi!
You do not thing that this is related to a CHROME issue ?
With FF works fine...
