### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by dnsmichi** [mocdaniel/dashing-icinga2#108]
I'm looking for people who want to maintain this project, including a full source code transfer. 

@mocdaniel I'd like to ask you whether you want to continue working on what we have built thus far :) 

Maybe others want to join on in too, like @bodsch who has experience here. 

## What's needed?

- The documentation is in the best shape I could ever create, limited to zero support questions. It also contains a full blown development docs to understand the changes.
- A bit of HTML, Ruby, JS/Coffee script knowledge. The code is readable according to community members.
- You might want to create a Dockerhub account and migrate the container builds too with then updating the docs

## Why?

I am fully transparent and don't want community members to be sitting in the dark.

Some things happened in the past months, and I started to build out a new perspective, new ideas which make me strong again. Some of you might have watched the 2.11 insights video, this was more or less a coming burnout on the whole Icinga topic. I've taken steps to protect myself, and stepped down from both my community work and contributions, I was just tired protecting the core backend thus fighting for the community needs on the project.

My new job at GitLab involves Prometheus and the observability stack as a whole, a new adventure starting fresh. This is where I see the future of cloud native environments and you'll see me around. 

My passion for creating a good demo and helping everyone with their office dashboard has gone beyond my usual open source contributions, all your feedback has driven me further. Even when times were rough after 2.11 being released, I found my motivation again with working on this lovely project again. Exactly when I was building the new ChartJS integration, we were on our way to GitLab Commit London.

After all, everything which happened was for the better, and I am happy :) Talk to you soon.

**Comment by mocdaniel** [comment]
First of all, thanks for being that transparent and taking the time to explain your measures!

I would gladly take a maintainer role for this project because I love what it offers to users who are willing to try new things and add to the project by themselves. That being said, I am not an expert on Ruby and just a mediocre user when it comes to HTML/JS, much of my proficiency has actually built up while using dashing-icinga over the course of the last year. Same goes for my participation within the Icinga community as a whole.

Therefore I would be glad if there  would be another maintainer who would take over responsibility together with me.

As for docker, I could migrate the container builds since I am maintaining some other images already, both for work and some freetime projects.

Let's sort this out and keep dashing-icinga alive and maintained, all the best for you at GitLab in the meantime!

**Comment by bodsch** [comment]
I had started my own dashing container some time ago to test my icinga2 gem. (And because I didn't like the spaghetti code at that time ;) )
Maybe it's time to merge the two repositories?
We'll see.
But it would be a shame if all that work fell through.

**Comment by dnsmichi** [comment]
@mocdaniel Thanks! When my time allows it, I will clean up the repository in the next days and then transfer it over to you. The next iteration can be to include @bodsch 's work, but don't feel stressed about it. You are not obligated to invest more time than you would want to :)

**Comment by dnsmichi** [comment]
@mocdaniel You'll need to delete your fork as otherwise I cannot transfer the repository.

**Comment by mocdaniel** [comment]
> @mocdaniel You'll need to delete your fork as otherwise I cannot transfer the repository.

Done

**Comment by dnsmichi** [comment]
@mocdaniel Done, thanks for taking over 👍 

There are some URL locations which you need to update unless they are not redirected after all. I will tweet about this transfer once and then wish you all the best with this lovely project :)

**Comment by mocdaniel** [comment]
> @mocdaniel Done, thanks for taking over 
> 
> There are some URL locations which you need to update unless they are not redirected after all. I will tweet about this transfer once and then wish you all the best with this lovely project :)

Thanks again for the work you put into this. I will look about the needed changes over the course of the week. :)

**Comment by dnsmichi** [comment]
@mocdaniel I truly believe in the passion we invest into Open Source, and I want to provide you with the best I can do :) This hopefully moves to even more exciting times 😎  

I don't know if you have a Twitter account to reply, here is the [tweet](https://twitter.com/dnsmichi/status/1257339090430763011).

**Comment by mocdaniel** [comment]
> @mocdaniel I truly believe in the passion we invest into Open Source, and I want to provide you with the best I can do :) This hopefully moves to even more exciting times 
> 
> I don't know if you have a Twitter account to reply, here is the [tweet](https://twitter.com/dnsmichi/status/1257339090430763011).

No twitter account, unfortunately. Thank you for the shout out anyways :) I am going to close this issue now.
