### ISSUE TITLE
I can't set TZ (TimeZone) for container

### ISSUE THREAD

**Issue by pilot513** [mocdaniel/dashing-icinga2#111]
Hello.
I want set timezone with var, when container run 
`-e TZ=America/New_York` 
but it's not worked for me.
`docker exec -it quizzical_margulis cat /etc/timezone`
Etc/UTC

**Comment by pilot513** [comment]
![image](https://user-images.githubusercontent.com/28645933/83272785-4a4e3700-a1d4-11ea-899f-4cfdd3b8682f.png)

**Comment by mocdaniel** [comment]
You are using the wrong environment variable name. Use 

`-e DASHBOARD_TIMEZONE=America/New_York` 

instead of `-e TZ=America/New_York` when running your container and it should work just fine, I just checked the behaviour.

**Comment by pilot513** [comment]
Very helpful! Thanks!
