### ISSUE TITLE
Question: Change data-sizey lower than 1?

### ISSUE THREAD

**Issue by Marco-Total** [mocdaniel/dashing-icinga2#116]
Hi,

is it possible to change the data-sizey to for example 0.5? My changes in the .erb file have no impact.

Thx, Rudi

**Comment by mocdaniel** [comment]
Hello Rudi,

this is not possible, the minimum for x and y values is 1, since they refer to the number of columns and rows, respectively, which the affected widgets will occupy in the dashboard.

Example:
```
data-sizex=1, data-sizey=1    # a 1x1 widget
data-sizex=2, data-sizey=1    # a 2x1 widget
data-sizex=1, data-sizey=3    # a 1x3 widget
```

**Comment by Marco-Total** [comment]
Ok, good to know, thank your for your answer!
