### ISSUE TITLE
Empty Icinga2-Dashboard

### ISSUE THREAD

**Issue by aristdm** [mocdaniel/dashing-icinga2#117]
I have the same issues as two other users with data not being shown in the icinga2-dashboard

I have tried almost everything mentioned on both users

- reinstalled, 3.0 (just sample data with no info). When restarts the data are shown in the dashboard then goes again when service comes up
- reinstalled 3.1 from tarball, same issue no data displayed
- reinstalled from git, same issue no data displayed

I'm out of hope. Can you help?

(removed pass on purpose)

<p>
icinga-srv:~$ tail -f /usr/share/dashing-icinga2/log/thin.log`
/usr/share/dashing-icinga2/lib/icinga2.rb:634:in `+'
/usr/share/dashing-icinga2/lib/icinga2.rb:634:in `block in getProblemServices'
/usr/share/dashing-icinga2/lib/icinga2.rb:620:in `each'
/usr/share/dashing-icinga2/lib/icinga2.rb:620:in `getProblemServices'
/usr/share/dashing-icinga2/lib/icinga2.rb:838:in `run'
/usr/share/dashing-icinga2/jobs/icinga2.rb:27:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job `
================================================================================
<p>First trying to read environment variables
Environment variables not found, falling back to configuration file config/icinga2.json
Detecting local config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Using config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Reading config{"icinga2"=>{"api"=>{"host"=>"localhost", "port"=>5665, "user"=>"dashing", "password"=>""}}, "icingaweb2"=>{"url"=>"http://localhost/icingaweb2"}, "dashboard"=>{"show_only_hard_state_problems"=>false, "timezone"=>"Europe/London"}}
<p>First trying to read environment variables
Environment variables not found, falling back to configuration file config/icinga2.json
Detecting local config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Using config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Reading config{"icinga2"=>{"api"=>{"host"=>"localhost", "port"=>5665, "user"=>"dashing", "password"=>""}}, "icingaweb2"=>{"url"=>"http://localhost/icingaweb2"}, "dashboard"=>{"show_only_hard_state_problems"=>false, "timezone"=>"Europe/London"}}
<p>First trying to read environment variables
Environment variables not found, falling back to configuration file config/icinga2.json
Detecting local config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Using config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Reading config{"icinga2"=>{"api"=>{"host"=>"localhost", "port"=>5665, "user"=>"dashing", "password"=>""}}, "icingaweb2"=>{"url"=>"http://localhost/icingaweb2"}, "dashboard"=>{"show_only_hard_state_problems"=>false, "timezone"=>"Europe/London"}}
<p>First trying to read environment variables
Environment variables not found, falling back to configuration file config/icinga2.json
Detecting local config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Using config file '/usr/share/dashing-icinga2/config/icinga2.local.json'.
Reading config{"icinga2"=>{"api"=>{"host"=>"localhost", "port"=>5665, "user"=>"dashing", "password"=>""}}, "icingaweb2"=>{"url"=>"http://localhost/icingaweb2"}, "dashboard"=>{"show_only_hard_state_problems"=>false, "timezone"=>"Europe/London"}}
<p>10.212.131.1 - - [04/Mar/2021 23:31:06] "GET /icinga2 HTTP/1.1" 200 7207 0.0180
10.212.131.1 - - [04/Mar/2021 23:31:06] "GET /events HTTP/1.1" 200 - 1146.2459
10.212.131.1 - - [04/Mar/2021 23:31:07] "GET /views/clock.html HTTP/1.1" 200 82 0.0012
10.212.131.1 - - [04/Mar/2021 23:31:07] "GET /views/list.html HTTP/1.1" 200 613 0.0011
10.212.131.1 - - [04/Mar/2021 23:31:07] "GET /views/meter.html HTTP/1.1" 200 375 0.0012
================================================================================`
`scheduler caught exception:
no implicit conversion of nil into String
/usr/share/dashing-icinga2/lib/icinga2.rb:634:in `+'
/usr/share/dashing-icinga2/lib/icinga2.rb:634:in `block in getProblemServices'
/usr/share/dashing-icinga2/lib/icinga2.rb:620:in `each'
/usr/share/dashing-icinga2/lib/icinga2.rb:620:in `getProblemServices'
/usr/share/dashing-icinga2/lib/icinga2.rb:838:in `run'
/usr/share/dashing-icinga2/jobs/icinga2.rb:27:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
===========================================================================
</P>

* Dashing version (`gem list --local dashing`):
dashing 1.3.7
* Ruby version (`ruby -V`):
ruby 2.5.5p157 (2019-03-15 revision 67260) (x86_64-linux-gnu)

* Version of this project (tarball name, tag name or `git show -1`):

* Operating System and version:
Debian 10 buster

* Client browser and version:
Chrome, Firefox, Edge

![image](https://user-images.githubusercontent.com/80074835/110045691-f82dd980-7d42-11eb-9939-15748f05b8d7.png)

![image](https://user-images.githubusercontent.com/80074835/110045733-0976e600-7d43-11eb-9539-557daa390fef.png)

**Comment by aristdm** [comment]
./restart-dashing: line 78: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
./restart-dashing: line 79: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/var/lib/gems/2.5.0/gems/thin-1.6.4/lib/thin/server.rb:107: warning: constant ::Fixnum is deprecated
Restarted Dashing with PID 8527 listening on port 8005.

**Comment by mocdaniel** [comment]
Hello @aristdm sorry for reacting so late - this issue slipped my attention for some reason. This looks like it might be the same bug as in #120 which was fixed by me yesterday. Could you fetch the newest commit from `master` and try again?
