### ISSUE TITLE
Pie-chart widgets render too big

### ISSUE THREAD

**Issue by vitekpetr** [mocdaniel/dashing-icinga2#123]
Hello,

I have installed Icinga 2 dashboard and I have an issue with the pie-chart widgets and labels.
The widgets render too big for the box and the labes are in grey color when they should be in white.

![image](https://user-images.githubusercontent.com/74969065/141944611-edca109f-8ca5-4247-863f-b7c3f91d1003.png)

There is an error in browser develepment console. Maybe it has something to do with the issue.
![image](https://user-images.githubusercontent.com/74969065/141944845-2bb40a62-39bb-4873-b08f-7212ba36024f.png)

  
* Dashing version: 1.3.7
* Ruby version: Ruby 2.7.0p0 (2019-12-25 revision 647ee6f091)
* Version of this project:
commit 5ed16c97f83863a0074dde847b2397c6ed49b7f8 (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel <dbodky@gmail.com>
Date:   Fri Aug 20 21:47:57 2021 +0200
diff --git a/Dockerfile b/Dockerfile
index e2d9fc9..9e18a11 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,6 @@
-FROM ruby:buster
+FROM ruby:2.7-buster
-MAINTAINER Michael Friedrich <michael.friedrich@gmail.com>
+MAINTAINER Daniel Bodky <dbodky@gmail.com>
 ENV LANG C.UTF-8
 ENV DEBIAN_FRONTEND noninteractive

* Modifications to this project, if any (`git diff`):
[icinga2.txt](https://github.com/mocdaniel/dashing-icinga2/files/7544491/icinga2.txt)

* Operating System and version: Ubuntu 20.04.3 LTS
* Client browser and version: Google Chrome verison 95.0.4638.69

**Comment by mocdaniel** [comment]
Fixed via #124 .
