### ISSUE TITLE
sharing dashboards

### ISSUE THREAD

**Issue by haytxy** [mocdaniel/dashing-icinga2#125]
is it possible to share dashboards between users and groups of users (using roles setup) ?

m

**Comment by mocdaniel** [comment]
No, not with dashing-icinga2's capabilities. It was designed as a dashboard for 'kiosk mode' usage and therefore does not take care of authenticating and authorizing users or groups. This isn't planned for the future, either.

Anyways, you could of course configure a web server or reverse proxy such as Apache2, nginx or Traefik to take care of this job, and redirect different user(groups) to different dashboards which you defined in dashing-icinga2.

Best,
Daniel

**Comment by haytxy** [comment]
@mocdaniel  @mocdaniel  so I can create different dashboards and for example, redistribute access to them by for example Icinga "Shared Navigation" feature. 

sry for this question... In dashing-Icinga2 I am able to create different Dashboards and when you use an exact Dashboard you will not have access to other dashboards, yes?

**Comment by mocdaniel** [comment]
Yes, you can create as many dashboards as you'd like by creating new files at `./dashboards`, they will be available via `http://yourdashingurl.com:8005/<dashboardname>`.

As for access control, you'd need to delegate this to a web server or similar service, as already mentioned.
