### ISSUE TITLE
Disable roundchart animation

### ISSUE THREAD

**Issue by Cube38282** [mocdaniel/dashing-icinga2#128]
Hello,

the 10sec refresh always replays the inital animation of the doughnut charts. 
Is it possible to disable said animations? If yes, could somebody please point me to the file containing this configuration?

Thanks in advance.

**Comment by mocdaniel** [comment]
You could take a look at [the ChartJS documentation regarding chart animations](https://www.chartjs.org/docs/latest/configuration/animations.html#animations). If this isn't good enough for you to fix the issue, feel free to ask again.

**Comment by Cube38282** [comment]
Thank you, I was able to disable the Animations in the Chart.bundle.js & Chart.bundle.min.js

**Comment by mocdaniel** [comment]
Glad I could point you in the right direction!
