### ISSUE TITLE
blank dashboard

### ISSUE THREAD

**Issue by cbnorman** [mocdaniel/dashing-icinga2#15]
everything seems to be working i do 
./restart-dashing -b /home/sysadmin/.gem/ruby/gems/dashing-1.3.7/bin/dashing
and then i can connect to a blank page host:8005/icinga2 it just has the icinga2 icon on the top left, no widgets. looking at cat ./log/thin.log i can see it pulling objects from my icinga instance just isnt doing anything with them?

![image](https://cloud.githubusercontent.com/assets/10809716/25271852/7e234320-267d-11e7-83ba-ef457c6ddef1.png)

**Comment by dnsmichi** [comment]
Strange. Browser type and version? Might be a local javascript caching issue. Or - what does the browser dev console say?

Btw - 1.2.0 provides a systemd service file in tools/systemd. You might want to try that one out too.

**Comment by dnsmichi** [comment]
Any feedback?

**Comment by vittel1** [comment]
Hey, I've got the same error. When I use Firefox on Ubuntu 16.04 it works perfectly.
On a Windows 7 machine with IE 11 it does not work.
If you need some other information, just ask. Hopes this helps.

**Comment by mcktr** [comment]
AFAIK Dashing is not supported by IE as described here Shopify/dashing#193

**Comment by dnsmichi** [comment]
I've seen that @bodsch talked about webrick and puma in the past. I don't know how much effort it would be to drop thin and use a different server. If you find something reasonable to support, your PRs could be added to v2.x.

**Comment by bodsch** [comment]
@dnsmichi o.O me?
okay, i plan a test with `puma`, but not with `webrick` ;)
`puma` is a simple replacement for `thin` and easy to implement.

**Comment by dnsmichi** [comment]
I'm waiting for someone to hack puma into here.

**Comment by dnsmichi** [comment]
Please continue in #47 which acts as a general issue to replace thin with something else, or find any other solution.
