### ISSUE TITLE
host down widget does not see downtime

### ISSUE THREAD

**Issue by p0ntsNL** [mocdaniel/dashing-icinga2#16]
The following def does not work properly, for some reason it does not exclude hosts that are in downtime:

its weird tho, because the same def is used by services, and that does work.

`def countProblems(objects)
    problems = 0

    objects.each do |item|
      item.each do |k, d|
        if (k != "attrs")
          next
        end

        if (d["state"] != 0 && d["downtime_depth"] == 0 && d["acknowledgement"] == 0)
          problems = problems + 1
        end
      end
    end

    return problems
  end`

**Comment by dnsmichi** [comment]
What exactly do you mean? Do you have any sample host data available from /v1/objects/hosts and their attributes (fetch with curl)?

**Comment by p0ntsNL** [comment]
Case can be closed, mistake on my side.

**Comment by dnsmichi** [comment]
Hint: You can close your own issues on GitHub :)
