### ISSUE TITLE
Verify dashboard, Javascript and browser versions 

### ISSUE THREAD

**Issue by dnsmichi** [mocdaniel/dashing-icinga2#19]
## Software

- [x] Dashboards and scriptlets were generated in 2015

```
commit fcedcb403295eaa05fbf5442cc35cfaeb6da9e96
Author: Michael Friedrich <michael.friedrich@netways.de>
Date:   Wed Sep 30 19:08:24 2015 +0200

    Initial import
```

- [x] Javascript versions

```
michi@mbmif ~/coding/icinga/dashing-icinga2 (master=) $ ls -la assets/javascripts/
total 456
drwxr-xr-x  8 michi  staff     272 Oct 16  2016 .
drwxr-xr-x  7 michi  staff     238 Jun 25  2016 ..
-rw-r--r--  1 michi  staff     869 Oct 16  2016 application.coffee
-rw-r--r--  1 michi  staff  143169 Sep 30  2015 d3-3.2.8.js
-rw-r--r--  1 michi  staff    1254 Sep 30  2015 dashing.gridster.coffee
drwxr-xr-x  4 michi  staff     136 Sep 30  2015 gridster
-rw-r--r--  1 michi  staff   20009 Sep 30  2015 jquery.knob.js
-rw-r--r--  1 michi  staff   61096 Sep 30  2015 rickshaw-1.4.3.min.js
```

- [x] Fonts

```
michi@mbmif ~/coding/icinga/dashing-icinga2 (master=) $ ls -la assets/fonts/
total 720
drwxr-xr-x  6 michi  staff     204 Sep 30  2015 .
drwxr-xr-x  7 michi  staff     238 Jun 25  2016 ..
-rw-r--r--  1 michi  staff   37405 Sep 30  2015 fontawesome-webfont.eot
-rw-r--r--  1 michi  staff  197829 Sep 30  2015 fontawesome-webfont.svg
-rw-r--r--  1 michi  staff   79076 Sep 30  2015 fontawesome-webfont.ttf
-rw-r--r--  1 michi  staff   43572 Sep 30  2015 fontawesome-webfont.woff
```

## Browsers

- [x] Chrome (Linux, Unix, Embedded only)
- [x] Firefox (Linux, Unix, Embedded only)
- [ ] Edge (Windows doesn't work)
- [x] Safari (macOS)

## Ideas

https://github.com/bodsch/docker-smashing#docker-dashing

**Comment by bodsch** [comment]
I found no reference for d3.js, jquery.knob.js and rickshaw-1.4.3.min.js in the smashing package.
I do not know where and if these are needed.
But, there are more recent versions and i will test this in my docker container.

this is also interessant: https://github.com/FlorianZ/dashing/commit/84edfc80775c87f679cecad4e68f6c84f67c8023 a replacment of batman.js with react.
I will ask the smashing people for this ...

**Comment by dnsmichi** [comment]
I've done the mentioned updates for the next release already, still they don't add much benefit. Pulling different sources might be tricky and should be discussed in a separate issue.
