### ISSUE TITLE
Dashing not workling when triying to connect to remote Icinga API

### ISSUE THREAD

**Issue by KKeXX** [mocdaniel/dashing-icinga2#32]
I try to start dashing on a different Server than the Icinga master host. The configuration for the API is set in `config/icinga2.json`, host is set to the hostname (or IP) of the Icinga master.

When I start dashing, with `dashing start -p 8005` these errors occure:
```
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:8005, CTRL+C to stop
================================================================================
scheduler caught exception:
403 "Tunnel or SSL Forbidden"
/usr/share/ruby/net/http/response.rb:119:in `error!'
/usr/share/ruby/net/http/response.rb:128:in `value'
/usr/share/ruby/net/http.rb:913:in `connect'
/usr/share/ruby/net/http.rb:862:in `do_start'
/usr/share/ruby/net/http.rb:851:in `start'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/resource.rb:51:in `get'
/usr/share/dashing-icinga2/lib/icinga2.rb:174:in `getApiData'
/usr/share/dashing-icinga2/lib/icinga2.rb:196:in `getIcingaApplicationData'
/usr/share/dashing-icinga2/lib/icinga2.rb:600:in `run'
/usr/share/dashing-icinga2/jobs/icinga2.rb:27:in `block in <top (required)>'
/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

When I adopt the host to localhost and forward the port 5665 via SSH tunnel to the remote Icinga master, everything works perfect.

Is a remote connection via API to a different host (Icinga master) not supported?

## Your Environment

* Dashing version (`gem list --local dashing`): dashing (1.3.7, 1.3.4)
* Ruby version (`ruby -v`): ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
* Version of this project (tarball name, tag name or `git show -1`): commit cc03aaafa489ede5a8b12d15e29b7fbef51bb0c8
* Operating System and version: RHEL 7.3

**Comment by bodsch** [comment]
`403 "Tunnel or SSL Forbidden"`
please check selinux!
turn it off and retest it

**Comment by KKeXX** [comment]
It's deactivated:
`~ # sestatus`
`SELinux status:                 disabled`

On both Hosts.

**Comment by dnsmichi** [comment]
I would believe that the Icinga 2 API is hidden behind a proxy or a tunnel and the connection attempt made by the rest-client Ruby library then fails with this error.

It seems that your Dashing server is not allowed to connect to proxy port 5665 (or what ever port you've configured in your local Dashing configuration).

**Comment by KKeXX** [comment]
@dnsmichi, you where right! I accidentally used a proxy, cause the `$http_proxy` variable was set. But that's not needed here. After clearing that, everything works as expected! Thanks for the hint.
