### ISSUE TITLE
Change Widget Color

### ISSUE THREAD

**Issue by odrino14** [mocdaniel/dashing-icinga2#43]
i Just move to dashing-icinga2 1.3.0 and i wanted to change the widget color from red to green like i did in 1.2.0 but it not working.
how can make it change it ?

**Comment by dnsmichi** [comment]
How did you change it in the old version?

**Comment by odrino14** [comment]
in the send_event i just change for example color from 'red' to 'green'. but.

```
#down, critical, warning, unknown
  my_host_color = host_down_adjusted.to_i > 0 ? 'red' : 'green'
  send_event('icinga-host-down', {
   value: host_down_adjusted.to_s,
   color: my_host_color
    })
```

**Comment by dnsmichi** [comment]
Look into the current code:

https://github.com/Icinga/dashing-icinga2/blob/master/jobs/icinga2.rb#L100

Neither the jobs code nor the library code will be the same on updates. There's no way to provide a stable interface -- you need to verify your code changes and re-apply them after an update, if they apply cleanly.

In this case, the event target changed.

**Comment by odrino14** [comment]
I know. it already compare both Code
i tried to change the color of unhandled host for example from red to green but it is not working.
```
puts "Host Down: " + icinga.host_count_problems_down.to_s
  send_event('icinga-host-problems-down', {
   value: icinga.host_count_problems_down.to_s,
   moreinfo: "All Problems: " + icinga.host_count_down.to_s,
color: 'green' })
```

**Comment by dnsmichi** [comment]
Please continue over at https://monitoring-portal.org
