### ISSUE TITLE
Dashboard API doesn't match attrs

### ISSUE THREAD

**Issue by skalessio** [mocdaniel/dashing-icinga2#44]
Hi, 

I tried to install dashing on a fresh installation of icinga2 and was failing all the time after a call
to the icinga2 API, after a bit of investigation i found that this request :
 
curl -H 'Accept: application/json' -k -s -u username:password -H 'X-HTTP-Method-Override: GET' -k 'https://testicinga1.samknows.com:5665/v1/objects/hosts' -d '{"attrs":["name","acknowledgement","downtime_depth","last_check"]}' 

was failing giving : *401 bad request*

seems that the equivalent value for **downtime_depth** now is called **last_in_downtime** 
i changed it in lib/icinga2.rb and it started to work.

i followed the icinga2 website for the installation and  `https://linoxide.com/monitoring-2/setup-monitoring-dashing-icinga2/` this to install dashing-icinga2.

Environment Info

dashing (1.3.7) : 
```
commit 14bc597af0dff11a0fe2883fa76b144860b7b9a0
Author: Michael Friedrich <michael.friedrich@icinga.com>
Date:   Wed Aug 23 20:15:05 2017 +0200

    Update screenshot
```

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
ubuntu 16.04
Google Chrome | 60.0.3112.113 (Official Build) (64-bit)

icinga2-bin:2.4.1-2ubuntu1
icinga2-common:2.4.1-2ubuntu1
icinga2-ido-mysql:2.4.1-2ubuntu1
icingaweb2:2.1.0-1ubuntu1.2
icingaweb2-module-doc:2.1.0-1ubuntu1.2
icingaweb2-module-monitoring:2.1.0-1ubuntu1.2
libicinga2:2.4.1-2ubuntu1
php-icinga:2.1.0-1ubuntu1.2
vim-icinga2:2.4.1-2ubuntu1

So, is my installation borked somehow or it's a true API change ?

**Comment by dnsmichi** [comment]
`downtime_depth` was added after v2.4. Seems you are using an outdated and unsupported Icinga 2 version. Please upgrade to v2.7 using the official package repository on packages.icinga.com
