### ISSUE TITLE
Dashing started but HTTP 404 on dashboards

### ISSUE THREAD

**Issue by ktella** [mocdaniel/dashing-icinga2#46]
Installed and started dashing as below and getting HTTP 404 when accessing the url. 

http://xxxxxxxxx.corp.xxxxxx.com:8080/icinga2

This may/may not be a BUG, but i need some help here.

[icinga@pdgllvnagios11 bin]$ ./dashing start -p 8080
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:8080, CTRL+C to stop
**10.98.202.162 - - [12/Oct/2017 11:18:56] "GET /icinga2 HTTP/1.1" 404 - 0.0015
10.98.202.162, 10.128.132.225 - - [12/Oct/2017 11:18:59] "GET /icinga2 HTTP/1.1" 404 - 0.0007
10.98.202.162 - - [12/Oct/2017 11:19:20] "GET /icinga2 HTTP/1.1" 404 - 0.0006
10.98.202.162, 10.128.132.225 - - [12/Oct/2017 11:19:21] "GET /icinga2 HTTP/1.1" 404 - 0.0005
10.98.202.162, 10.128.132.225 - - [12/Oct/2017 11:19:48] "GET /icinga2 HTTP/1.1" 404 - 0.0007
10.98.202.162 - - [12/Oct/2017 11:19:50] "GET /icinga2 HTTP/1.1" 404 - 0.0006
10.98.202.162 - - [12/Oct/2017 11:20:14] "GET /icinga2 HTTP/1.1" 404 - 0.0005
10.98.202.162, 10.128.132.225 - - [12/Oct/2017 11:20:17] "GET /icinga2 HTTP/1.1" 404 - 0.0006
**

## Expected Behavior

Expected to access icinga2 dashboard.

## Current Behavior

HTTP 404

## Possible Solution
 unknown as of now.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Dashing version (`gem list --local dashing`): dashing (1.3.7)
* Ruby version (`ruby -V`):ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
* Version of this project (tarball name, tag name or `git show -1`): Current Master
* Modifications to this project, if any (`git diff`): NONE
* Operating System and version: RHEL 7.2
* Client browser and version: All browsers

**Comment by dnsmichi** [comment]
Please continue on the community support channels, e.g. monitoring-portal.org
