### ISSUE TITLE
2.8.0 Icinga Plugin shows Menu

### ISSUE THREAD

**Issue by MartinEgli** [mocdaniel/dashing-icinga2#50]
## Current Behavior

After update to IcingaWeb 2.8 the icinga plugin shows the menu bar.

![image](https://user-images.githubusercontent.com/7021413/33422309-91038774-d5b5-11e7-8ac2-28683b44beda.png)

**Comment by dnsmichi** [comment]
That's an issue in Icinga Web 2 with either showCompact or fullScreen. Please refer to icinga/icingaweb2#3169

**Comment by MartinEgli** [comment]
OK
