### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by deric** [mocdaniel/dashing-icinga2#55]
Hi,

I've created a simple Docker image based on Debian 9: https://github.com/deric/docker-icinga2-dashing
It might make easier to test the dashing project. Would you accept a PR with a `Dockerfile`?

Would it be possible to tag a new release, so that the latest changes are included under some tag? 

Running dashing should be quite easy (but currently requires version from github master branch):
```
docker run -it -p 8005:8005\
 -e ICINGA2_API_HOST='localhost'\
 -e ICINGA2_API_PORT=5665\
 -e ICINGA2_API_USERNAME='root'\
 -e ICINGA2_API_PASSWORD='icinga'\
 deric/icinga2-dashing:master
```

**Comment by dnsmichi** [comment]
I'm planning for a new release at Icinga Camp Berlin, I have some local un-pushed changes floating around.

I'm not sure about Docker though, my experience is that everyone has different expectations. Once you have such a container, users want support that I am not willing to provide.

I would add an example for Docker into the README.md file and leave the choice to the user :)

**Comment by dnsmichi** [comment]
After thinking about it for a while, I don't want to maintain yet another Dockerfile. If anyone wants to make use of this project in their container images, feel free to do so. Blog about it, share the integration on the forums, work together with others, etc. 

Sorry & thanks for the offer 👍

**Comment by dnsmichi** [comment]
I've changed my mind with 1) working with GitHub actions & GItLab CI recently 2) now maintaining this for myself without Icinga relation. #85 puts everything together.
