### ISSUE TITLE
Multiple Dashboards Fuzzy

### ISSUE THREAD

**Issue by aledr** [mocdaniel/dashing-icinga2#56]
Hi!

I'm running multiple dashboards and for each one I generate a file in "config", "dashboards" and "jobs".
What I'm trying to achieve is to create a single dashboard for each customer to show his only informations.

I set one specific user to each config file and then set unique identifiers for the events in dashboards and jobs files.

The API users are limited to the specific customer hostgroup:

api-users.conf
```
object ApiUser "dashing-user1" {
    password = "user1_dashing"
    permissions = [
        {
            permission = "status/query"
        },
        {
            permission = "objects/query/*"
            filter = {{ "customer_name_here" in host.groups }}
        }
    ]
}
```

Problem is that instead of getting the correct number for hosts and services count the numbers are just fuzzy and alleatory.

Is this the correct way to generate multiple dashboards?

Thanks.

**Comment by dnsmichi** [comment]
Multiple dashboards are out of the scope for this project, but still, limiting the API received objects is one of them. I would extract the object queries and verify that returned numbers by Icinga 2 are correct for this specific user.

**Comment by aledr** [comment]
Seems something is mixed in the dashing-icinga2 /events channel.
Even filtering on the Icinga2 API, dashing-icinga2 is able to query objects out of the filter.

Are you available to a 1:1 session?

**Comment by dnsmichi** [comment]
If you need (development) support, you can kindly send an email to info@icinga.com to discuss things further.

As said, this project is built for just one job and dashboard. From my experience, multiple jobs pulling the same data do not make much sense, as they slow down Dashing and pollute the connection with lots of data pulled. I would rather investigate on a feature to allow sending events to specific dashboards, with predefined filters, from one job only. Though I don't know if Dashing provides such possibilities.

**Comment by dnsmichi** [comment]
I'm not planning to look into this, so I'm closing here.
