### ISSUE TITLE
Remove problems tile

### ISSUE THREAD

**Issue by ajayan769** [mocdaniel/dashing-icinga2#59]
Is there any option to remove "Problems" tile from the dashing view?

**Comment by mcktr** [comment]
Hi,

you have to edit the `icinga2.erb` file that is contained in the `dashboards` folder. In the file you must remove the following lines:

```
<!-- Takes two rows for all service problems by severity -->
<li data-row="1" data-col="4" data-sizex="1" data-sizey="2">
  <div data-id="icinga-severity" data-view="List" data-unordered="true" data-title="Problems"></div>
</li>
```

After restarting dashing and reloading the page the Problems tile should be gone.

Best regards
Michael

**Comment by dnsmichi** [comment]
As @mcktr said, you need to edit the dashboard itself. There is no support for enabling or disabling specific widget on the dashboard, this one serves as a demo and basis for your own dashboards. You are encouraged to create such and build your own views.

**Comment by ajayan769** [comment]
@mcktr @dnsmichi  Thank you so much for the help, it helped  :D
