### ISSUE TITLE
Vertical monitor allign

### ISSUE THREAD

**Issue by linuxmail** [mocdaniel/dashing-icinga2#60]
hi,

with the new allign in the  middle, I can't get everything fit on a vertical screen and I have to scroll to the right. Which CSS part I have to change, so that I have nearly no empty space on both sides ?

cu denny

**Comment by dnsmichi** [comment]
The layout always has been centered, the background image might influence that with its stretched mode.

`assets/stylesheets/application.scss` holds the generic SCSS declarations.

**Comment by linuxmail** [comment]
hi,

ok. Thanks. I try to find it :-)
