### ISSUE TITLE
Don't display acknowledged services in "problems" panel

### ISSUE THREAD

**Issue by log1-c** [mocdaniel/dashing-icinga2#61]
Currently the default dashboard also lists already acknowledge service problems in the problems panel.
Imo only the unacknowledged/new problems should be listed there

## Your Environment
* Version of this project (tarball name, tag name or `git show -1`): Realease v2.0.0
commit 40fd28144ce4778e838a4d36d2d0b2b8764bbffa

**Comment by dnsmichi** [comment]
The listing takes the severity into account, and previous patches grouped them by state.

https://github.com/Icinga/dashing-icinga2/blob/master/lib/icinga2.rb#L435

I do see your point, but that renders severity calculation obsolete. You can do so in your job and filter that away before service_problems_severity is processed.

**Comment by log1-c** [comment]
hi @dnsmichi,

thank you for your response.
I tried commenting various lines in /lib/icinga2.rb or /jobs/icinga2.rb leading to either no changes or an emtpy Problems panel.

Could you tell me what I need to change in the files, if it is not too much effort!
Else I will try some more commenting combinations or leave it as is xD

Best regards and thanks for all your effort!

**Comment by thekoma** [comment]
I've solved creating a filter on the api user:
```
object ApiUser "dashboard-user"  {
  password = "averysecretpasswordnooneknowsforsomereason"
  permissions = [
  {
    permission = "objects/query/Host"
    filter = {{ host.downtime_depth == 0 && host.acknowledgement == 0 && host.flapping == false }}
  },
  {
    permission = "objects/query/Service"
    filter = {{ service.downtime_depth == 0 && service.acknowledgement == 0 && service.flapping == false }}
  },
  {
    permission = "status/query"
  },
  {
    permission = "types"
  }, ]
}
```

**Comment by dnsmichi** [comment]
I'll think about how to make this more generic. I just don't have time to look into Ruby code atm.

**Comment by log1-c** [comment]
Thanks @koma85, haven't thought of that!

**Comment by dnsmichi** [comment]
Use this suggestion: https://github.com/dnsmichi/dashing-icinga2/issues/61#issuecomment-375018395 as I won't look into the details for the Ruby parts, sorry.
