### ISSUE TITLE
Empty values in dashing-icinga2

### ISSUE THREAD

**Issue by redbob365** [mocdaniel/dashing-icinga2#63]
I installed dashing-icinga, but it's empty. Look at image:

![empty-dashing](https://imgur.com/download/0JN00hE)

but Icinga2 is running fine. Look:
![running-icinga](https://imgur.com/download/Lp6qBlL)

Any ideas?

* Dashing version: 1.3.7
* Ruby version: 2.3.1p112
* Version of this project (tarball name, tag name or `git show -1`): commit b24d06ceaa9a99e3f4c01c476f63c3d37ef28e0e
* Modifications to this project, if any (`git diff`): none
* Operating System and version:  ubuntu  16.04.4 64bit
* Client browser and version: Firefox 38esr

**Comment by redbob365** [comment]
After rebooting the server, now values are populated... but what does it mean these two empty values at bottom?
[Icinga-404values](https://imgur.com/download/sn9dEgv)

**Comment by mcktr** [comment]
The two widgets at the bottom display host and service problems from Icinga Web 2. You can configure your Icinga Web 2 URL in `config/icinga2.json` or, if you don't want to use the widgets, you can remove them by editing `dashboards/icinga2.erb`.

**Comment by redbob365** [comment]
Great!
I changed `localhost` by `<Server IP>` at `config/icinga2.json`, now it runs fine. Thanks!
[dashing-ok](https://imgur.com/download/1aDE57O)
