### ISSUE TITLE
How to add multiple Icinga2 instances

### ISSUE THREAD

**Issue by sammcj** [mocdaniel/dashing-icinga2#64]
We're looking at using Icinga2 but it looks like it doesn't currently support being used as a dashboard for any more than a single Icinga2 instance.

How hard would it be to add multiple Icinga2 servers to this project?
Is it something you're looking at doing?

Thanks :)

**Comment by dnsmichi** [comment]
You might create your own dashboard with different instances of the icinga class object and different configuration settings retrieved from a config file. The calculated value attributes and exported functions could then be used for further calculations.

I'm not planning with any features for this project, for me it is sort of "feature complete" :)

**Comment by sammcj** [comment]
No worries, thanks for such a quick response!

--
Sam McLeod
