### ISSUE TITLE
Add a better indicator for 0 unhandled problems for Simplelist

### ISSUE THREAD

**Issue by codingwatermelon** [mocdaniel/dashing-icinga2#65]
## Expected Behavior

Hi there,

I'd like a better indication for when there are 0 unhandled problems for Hosts and Services in the Simplelist widget. See this picture:

![simplelist](https://user-images.githubusercontent.com/32379178/39905187-bf8cb2e6-5477-11e8-8ff4-38e1e43bf914.png)

When there are 0 unhandled problems (for host problems in this case), there is this big empty space that I wish had a way of conveying that there are no problems in.

One way of achieving this might be creating a green line or box within this box with the number "0" or "OK". Perhaps another option would be to make the entire tile green and have "0" in the middle. I think it would just look better, similarly to how the Meter widget to the left of it has a meter with 0.

I just think it throws off the look and feel of the dashboard when there is a giant tile with text only at the top and bottom. 

What do you think?

Thanks!
watermelon

**Comment by dnsmichi** [comment]
I do see it in a way that this only is a problem dashboard, where no green will be shown anywhere. Different colours should only be used when something is broken. Previous patches had a green zero, then other patches removed it again.

There's no right and wrong here, I'll leave it in the current implementation state and let others fork the repository and create their own dashboards if needed.
