### ISSUE TITLE
setting permissions to exclude network devices. 

### ISSUE THREAD

**Issue by MartinVUC** [mocdaniel/dashing-icinga2#66]
Im looking for a way to exclude devices thats not a part of a certain hostgroup in Icinga2. 

My /etc/icinga2/conf.d/api-users.conf looks like this as of now. 

/**
 * The APIUser objects are used for authentication against the API.
 */
object ApiUser "director" {
  password = "Kodeord1"
  // client_cn = ""

  permissions = [ "*" ]

object ApiUser "dashing" {
  password = "Kodeord1"
  permissions = [
    {
            permission = "status/query"
        },
        {
            permission = "objects/query/*"
            filter = {{ "tekniker" in host.groups }}
        }
    ]
}

This does not seem to work. Any suggestions as how to make the dashing user only show host and service notifications from the hostgroup "tekniker"?

**Comment by dnsmichi** [comment]
Please continue on https://monitoring-portal.org, this is where the community may help.
