### ISSUE TITLE
Dashboard iFrame without authentication

### ISSUE THREAD

**Issue by taalas** [mocdaniel/dashing-icinga2#67]
Hi,

the iFrames at the bottom currently only work if the browser has a valid authenticated session with Icinga Web. Is this correct? Is there any way to have the dashboard retrieve the information without authentication (but without disabling authentication altogether)?

**Comment by dnsmichi** [comment]
Iframes do not allow to pass authentication information, neither hardcoded in the URL nor with anything else. 

You'll need to login once the page is loaded, or you provide an instance of Icinga Web 2 which is read only and requires no auth (e.g. with a specific IP address space configured in Apache/Nginx there).

This isn't specific to Icinga Web 2 or Dashing, more of a general security implementation in the HTML standard. Unfortunately there isn't a fix for this, so closing this issue.
