### ISSUE TITLE
Communication with Certificates

### ISSUE THREAD

**Issue by phil-or** [mocdaniel/dashing-icinga2#69]
## Current Behavior

We use a dedicated Server for dashing-icinga2 and are very happy with it. The communication with Icinga2 is done so far via the API user + password. Now we would like to switch to a communication with certificates. After I have carried out all necessary steps as described in the instructions, I get the following error messages:
Dashing-Log: 

> scheduler caught exception:
> 401 Unauthorized

Icinga2-Log:
> information/ApiListener: New client connection for identity 'dashing-server' from [x.x.x.x.]:34900 **(no Endpoint object found for identity)**
> information/HttpServerConnection: Request: GET /v1/status/IcingaApplication (from [x.x.x.x]:34900), user: <unauthenticated>)
> warning/HttpServerConnection: Unauthorized request: GET /v1/status/IcingaApplication

The connection works, but why does Icinga2 need an endpoint object?

_
## Your Environment

* Dashing version (`gem list --local dashing`): 1.3.7
* Operating System and version: CentOS7

**Comment by dnsmichi** [comment]
That's an information level, no warning. The real error is that the user cannot authenticate, likely a problem with the user, there isn't any passed inside the HTTP request.

**Comment by phil-or** [comment]
Thank you for your hint. The user was configured incorrectly in api.conf

If api.conf looks like this, it works:

/etc/icinga2/features-available/api.conf
> object ApiUser "dashing" {
>   client_cn = "dashing-server"
> }
