### ISSUE TITLE
Dashing cache problem ?

### ISSUE THREAD

**Issue by CyberBison** [mocdaniel/dashing-icinga2#7]
Hi !
I have a big problem with the dashing and I think it could possibly comes from the cache (but not sure). It was working really well on all of my computers and suddenly it stopped working on my working laptop. No informations are showed except the ones in the iframe, as you can see there:
![image](https://cloud.githubusercontent.com/assets/8091411/22037398/44c26acc-dcf7-11e6-90f7-81a833b23fe5.png)

Although, I've tested on different dashing demo and... no one is working anymore on my laptop.
What is weird here is that it's working like a charm on my others computer. I've looked with one of my colleague and he has the exact same problem: it works on certains computers and doesn't work anymore on the others...
On computers concairned by the bug: it doesn't work on any browser (from Firefox to Chrome).

Thanks for your help and sorry for the bad english :)

**Comment by dnsmichi** [comment]
Hm, which version of dashing-icinga2 is that? That looks sort of modified. Furthermore which software versions of ruby, dashing etc are involved here? 

From a first peek I'd say local browser cache.

**Comment by CyberBison** [comment]
We've just changed the background color and modified the order :)
But we use the latest version of everything (it's a fresh install, less than a week).

We've checked and it seems to be related to the generation of the "events" file. As you can see, it doesn't load:
![image](https://cloud.githubusercontent.com/assets/8091411/22065016/82f1c786-dd86-11e6-867f-f268f0c21dc5.png)

On my second laptop, it loads without any problem.
I've noticed that after approximatively 30 minutes without refreshing the page, it suddenly works again. But if I manually refresh after that, same problem; events file isn't loaded.

**Comment by dnsmichi** [comment]
Dashing itself is the binary application which serves the custom dashboards, widgets, jobs. By default it is running thin (which is what you get from ps aux) and allows for additional logging. I would investigate on that part, and probably also try a "default" job runner to see whether it works there, or not. Based on that troubleshooting I'd then try to investigate on the icinga2 job.

Sometimes specific browsers and versions do not work with the involves javascript events, or similar. That's why I was asking about the specific versions, browser as well as Dashing plus ruby gems.

Though maybe it might be worthwhile to check their issue tracker for similarities.

**Comment by geoffhouse** [comment]
I'm having (perhaps) the same problem.
Steps to reproduce:
- restart dashing (either foreground or daemon)
- go to http://ipaddress/events in browse
- page doesn't load

In fact, it only loads when you stop dashing (ctrl-c). This explains the behaviour in the UI. If I reload the html page, I don't get valid data until I restart dashing.

Is something blocking on the events page?

- fresh install on 16.03.2017
- Ubuntu 14.04.5
- ruby 1.9.3p484
- thin 1.6.4
- browsers:
--- chrome (as described)
--- wget (as described)
--- same, although it ends up showing an error page rather than the results data

**Comment by dnsmichi** [comment]
As previously said, it is tremendously hard to debug Dashing itself. I have seen the refreshing problem a couple of times, but was never able to reliable reproduce nor analyse the issue. It also might be worthwhile to disable several widgets (and their `send_event` call in `jobs/icinga2.rb`) and check whether this solves your issue or not. If you're a JS developer you'll probably could peek into the JavaScript code itself which is used for rendering and refreshing.

**Comment by mmarodin** [comment]
Hi.

I've the same problem, /events is not working until I stop the daemon, so I can see the dashboard with some data only after that.

This is my environment:
- Oracle Linux 7.3 (RHEL like system)
- ruby 2.0.0p648
- thin (1.6.4)

**Comment by dnsmichi** [comment]
As said, there is nothing I can do. Dig into the Dashing sources and analyse why the events are failing. Maybe someone finds a Dashing issue id or a patch.

**Comment by mmarodin** [comment]
Ok, thanks.
I've dashing (1.3.7), what's your release?

**Comment by bodsch** [comment]
dashing hold no data into a cache.
under the hood, runs separated jobs (written in ruby or an other programming language) the push information to the used widgets.
can you give me a screenshot from the web developer console (chrome or firefox) or an sample of a curl call (with -v argument)?

**Comment by mmarodin** [comment]
These are my screenshots:
![icinga2_dashing01](https://user-images.githubusercontent.com/2854369/27632307-9dd5f1b4-5bfb-11e7-98fd-edccb10248b0.png)
![icinga2_dashing02](https://user-images.githubusercontent.com/2854369/27632763-07ab5fa6-5bfd-11e7-86f3-4667f7591305.png)
![icinga2_dashing03](https://user-images.githubusercontent.com/2854369/27632326-a7164652-5bfb-11e7-8c95-638de09a9ff2.png)

**Comment by bodsch** [comment]
you can find a dashing logfile here: /tmp/dashing.log

can you post the logfile?

**Comment by mmarodin** [comment]
There is no /tmp/dashing.log, I have /usr/share/dashing-icinga2/log/thin.log:
_Writing PID to tmp/pids/thin.pid
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:8005, CTRL+C to stop
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.5833333333333334, "active_host_checks_15min"=>533.0, "active_host_checks_1min"=>35.0, "active_host_checks_5min"=>177.0, "active_service_checks"=>8.516666666666667, "active_service_checks_15min"=>8487.0, "active_service_checks_1min"=>511.0, "active_service_checks_5min"=>2827.0, "avg_execution_time"=>0.5964878687529391, "avg_latency"=>0.0008162203832432087, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>74.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>29.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793223.8083159924}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>35.0}, {"label"=>"Service (active)", "value"=>511.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]
192.168.0.252 - - [06/Jul/2017 16:28:35] "GET /icinga2 HTTP/1.1" 200 4437 0.0043
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.5833333333333334, "active_host_checks_15min"=>533.0, "active_host_checks_1min"=>35.0, "active_host_checks_5min"=>177.0, "active_service_checks"=>8.566666666666666, "active_service_checks_15min"=>8490.0, "active_service_checks_1min"=>514.0, "active_service_checks_5min"=>2826.0, "avg_execution_time"=>0.5965565624745514, "avg_latency"=>0.0008159844906299145, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>73.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>30.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793228.7846820354}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>35.0}, {"label"=>"Service (active)", "value"=>514.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]
192.168.0.252 - - [06/Jul/2017 16:28:39] "GET /views/meter.html HTTP/1.1" 200 336 0.0014
192.168.0.252 - - [06/Jul/2017 16:28:39] "GET /views/list.html HTTP/1.1" 200 609 0.0006
192.168.0.252 - - [06/Jul/2017 16:28:39] "GET /views/simplemon.html HTTP/1.1" 200 223 0.0006
192.168.0.252 - - [06/Jul/2017 16:28:39] "GET /views/iframe.html HTTP/1.1" 200 52 0.0006
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.45, "active_host_checks_15min"=>528.0, "active_host_checks_1min"=>27.0, "active_host_checks_5min"=>177.0, "active_service_checks"=>8.616666666666667, "active_service_checks_15min"=>8492.0, "active_service_checks_1min"=>517.0, "active_service_checks_5min"=>2835.0, "avg_execution_time"=>0.5973724131704762, "avg_latency"=>0.0008153196727259878, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>73.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>30.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793233.7709600925}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>27.0}, {"label"=>"Service (active)", "value"=>517.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.4666666666666667, "active_host_checks_15min"=>529.0, "active_host_checks_1min"=>28.0, "active_host_checks_5min"=>175.0, "active_service_checks"=>8.7, "active_service_checks_15min"=>8495.0, "active_service_checks_1min"=>522.0, "active_service_checks_5min"=>2837.0, "avg_execution_time"=>0.5973184988748025, "avg_latency"=>0.0008162011533099662, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>73.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>30.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793238.7218999863}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>28.0}, {"label"=>"Service (active)", "value"=>522.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.5166666666666667, "active_host_checks_15min"=>532.0, "active_host_checks_1min"=>31.0, "active_host_checks_5min"=>177.0, "active_service_checks"=>8.35, "active_service_checks_15min"=>8497.0, "active_service_checks_1min"=>501.0, "active_service_checks_5min"=>2836.0, "avg_execution_time"=>0.5971936882153327, "avg_latency"=>0.0008161287151292343, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>73.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>30.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793243.6796069145}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>31.0}, {"label"=>"Service (active)", "value"=>501.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.5833333333333334, "active_host_checks_15min"=>532.0, "active_host_checks_1min"=>35.0, "active_host_checks_5min"=>177.0, "active_service_checks"=>8.616666666666667, "active_service_checks_15min"=>8498.0, "active_service_checks_1min"=>517.0, "active_service_checks_5min"=>2838.0, "avg_execution_time"=>0.5990499876495591, "avg_latency"=>0.000818469715053222, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>73.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>30.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793248.6334400177}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>35.0}, {"label"=>"Service (active)", "value"=>517.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.5833333333333334, "active_host_checks_15min"=>531.0, "active_host_checks_1min"=>35.0, "active_host_checks_5min"=>177.0, "active_service_checks"=>8.483333333333333, "active_service_checks_15min"=>8483.0, "active_service_checks_1min"=>509.0, "active_service_checks_5min"=>2821.0, "avg_execution_time"=>0.5986868122710973, "avg_latency"=>0.0008196090071150806, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>73.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>30.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793253.5866661072}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>35.0}, {"label"=>"Service (active)", "value"=>509.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]
App Info: {"icingaapplication"=>{"app"=>{"enable_event_handlers"=>true, "enable_flapping"=>true, "enable_host_checks"=>true, "enable_notifications"=>true, "enable_perfdata"=>true, "enable_service_checks"=>true, "node_name"=>"myprefix-mon01.ipa.mydomain.com", "pid"=>27466.0, "program_start"=>1498558087.525085, "version"=>"v2.6.2"}}}
CIB Info: {"active_host_checks"=>0.5833333333333334, "active_host_checks_15min"=>531.0, "active_host_checks_1min"=>35.0, "active_host_checks_5min"=>177.0, "active_service_checks"=>8.833333333333334, "active_service_checks_15min"=>8497.0, "active_service_checks_1min"=>530.0, "active_service_checks_5min"=>2839.0, "avg_execution_time"=>0.5983273489216135, "avg_latency"=>0.0008007474574664644, "max_execution_time"=>32.53084087371826, "max_latency"=>0.42885828018188477, "min_execution_time"=>0.0, "min_latency"=>0.0, "num_hosts_acknowledged"=>7.0, "num_hosts_down"=>9.0, "num_hosts_flapping"=>0.0, "num_hosts_in_downtime"=>0.0, "num_hosts_pending"=>0.0, "num_hosts_unreachable"=>0.0, "num_hosts_up"=>174.0, "num_services_acknowledged"=>12.0, "num_services_critical"=>73.0, "num_services_flapping"=>0.0, "num_services_in_downtime"=>0.0, "num_services_ok"=>2788.0, "num_services_pending"=>0.0, "num_services_unknown"=>35.0, "num_services_unreachable"=>68.0, "num_services_warning"=>30.0, "passive_host_checks"=>0.0, "passive_host_checks_15min"=>0.0, "passive_host_checks_1min"=>0.0, "passive_host_checks_5min"=>0.0, "passive_service_checks"=>0.0, "passive_service_checks_15min"=>0.0, "passive_service_checks_1min"=>0.0, "passive_service_checks_5min"=>0.0, "uptime"=>793258.5438170433}
Meter widget: Hosts 2.0/183 Services 126.0/2926
Checks: [{"label"=>"Host (active)", "value"=>35.0}, {"label"=>"Service (active)", "value"=>530.0}]
Severity: [{"label"=>"myprefix-ap1240-03 - uptime"}, {"label"=>"myprefix-ap1240-03 - client"}, {"label"=>"myprefix-ap1240-03 - load"}, {"label"=>"myprefix-ap1240-03 - memory"}, {"label"=>"myprefix-ap1240-04 - uptime"}]_

**Comment by bodsch** [comment]
the connection to the icinga2 is okay and the library reads corrects data:
`Meter widget: Hosts 2.0/183 Services 126.0/2926`

I will try to adjust your problem

**Comment by mmarodin** [comment]
Thanks, please let me know

**Comment by bodsch** [comment]
i found no problems in my test setup.
which browser are used?
have you tested a newer version?
or an alternative?

**Comment by mmarodin** [comment]
I've tested it on my Windows client, with Firefox 45.9.0 ESR, Firefox Portable 24.7.0 ESR, Internet Explorer 11.0.44, Microsft Edge 38.14393 and Google Chrome 60.0.3112.101, same problem.
And from other Windows clients same problem.

But I've just tried to test it from a test Linux client, with Firefox 50.1.0, and it works!

It seems to be a Windows problem. Have you any idea about it?
I tried to disable the Windows firewall, but it didn't works ...

Please let me know, thanks

**Comment by dnsmichi** [comment]
Rumors say that Dashing doesn't work on Windows clients at all, but I did not verify that information. Can you reproduce the issue with a simple demo install of a dashing "default" dashboard, or any other demo dashboard found on the net?

**Comment by mmarodin** [comment]
I've tried this URL: http://dashingdemo.herokuapp.com/sample
From my Windows client it doesn't work, from my Mac client works.

So it seems a Dashing problem, but in the project page they don't say anything about Windows OS issues, only about IE ... grrr

**Comment by mmarodin** [comment]
This issue go on [here](https://github.com/Smashing/smashing/issues/83)

**Comment by dnsmichi** [comment]
Please continue in #47 which acts as a general issue to replace thin with something else, or find any other solution.
