### ISSUE TITLE
Upgrading dashing-icinga2

### ISSUE THREAD

**Issue by redbob365** [mocdaniel/dashing-icinga2#71]
Hi, 

I wanna upgrade Dashing, because my monitor computer is not loading dashboards, due to overloading (I guess an upgrade will turn things better...)

- Will I copy new version and paste over existing ones?
- Is there a ruby gem specific command to do this?

Thanks,

## Your Environment
* Dashing version (`gem list --local dashing`): dashing (1.3.7, 1.3.4) (why two dashings?)
* Ruby version (`ruby -V`): 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
* Version of this project (tarball name, tag name or `git show -1`):  dunno how do it
* Modifications to this project, if any (`git diff`): dunno how to do it
* Operating System and version: ubuntu 16.04
* Client browser and version: Firefox 63.0

**Comment by dnsmichi** [comment]
There's no upgrade strategy for own modifications. You'll need to start with a fresh clone, and apply your own changes to it. If you didn't do any, and created a custom configuration file like suggested in the docs, you're safe to just copy the new content over, and re-run `bundle install`.

The whole project serves as a demo playground and start for own dashboards, so there's no ruby gem or alike.

**Comment by redbob365** [comment]
OK, Thanks! I will apreciate it.
