### ISSUE TITLE
Two lower panels (iframes) not showing content

### ISSUE THREAD

**Issue by smashplay** [mocdaniel/dashing-icinga2#75]
Hi,

as mentioned in the title the iframes won't show content, despite I'm logged into icinga in the current browser session. On the localhost (icingaweb2 and dashing-icinga) is a login-mask shown (only error code after login). On a remote host it says: connection refused.

While starting in foreground i got the following error:

`root@skynet:/usr/share/dashing-icinga2# dashing start -p 8005
First trying to read environment variables
Using environment variable configuration on 'localhost:5665 '.
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:8005, CTRL+C to stop
================================================================================
scheduler caught exception:
401 Unauthorized
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:51:in `get'
/usr/share/dashing-icinga2/lib/icinga2.rb:236:in `getApiData'
/usr/share/dashing-icinga2/lib/icinga2.rb:258:in `getIcingaApplicationData'
/usr/share/dashing-icinga2/lib/icinga2.rb:662:in `run'
/usr/share/dashing-icinga2/jobs/icinga2.rb:27:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================`

dashing (1.3.7)
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

icinga:
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-6-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: x86-ubc-01

dashing-icinga:
commit 69f40895bab9219e3a03b4ebbe25534cea0cb892

no mods (yet;))

**Comment by dnsmichi** [comment]
The error originates from wrong API credentials. Also, the URL base for Icinga Web 2's iframe needs to be configured. Please move such questions to https://community.icinga.com in the future.
