### ISSUE TITLE
Blank dashboard with console-log "EventSource's response has a MIME type ("text/html") that is not "text/event-stream"

### ISSUE THREAD

**Issue by mocdaniel** [mocdaniel/dashing-icinga2#76]
I installed dashing as instructed in the readme-section and opened up the dashboard, but it's showing just the background and empty tiles. Chrome Devtools' network-tab is showing me that the following assets and scrips are loaded:
* icinga2
* application.js
* application.css
* log-icinga-inv.png
* events
* icinga-hero-background.jpg
* list.html
* meter.html
* simplelist.html
* iframe.html
* favicon.png
The console is showing the error **EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.**

I already did some research in that case and got hints that it might be due to my Apache-configuration, with the relevant parts currently looking as follows:

**httpd.conf**
```
DocumentRoot "/usr/share/icingaweb3/public"

#
# Relax access to content within /var/www.
#

<VirtualHost *:80>
    ServerName server.domain.network.com

    ProxyPreserveHost On
    ProxyRequests On
    # LogLevel alert rewrite:trace6
    RewriteEngine On
</VirtualHost>
```
and the separate config for things concerned with dashing-icinga:

```
<Location /icinga2>
      ProxyPass http://localhost:8005/icinga2
      ProxyPassReverse http://localhost:8005/icinga2
</Location>

<Location /assets/>
      ProxyPass http://localhost:8005/assets/
      ProxyPassReverse http://localhost:8005/assets/
</Location>
```

Any help is appreciated, I can upload screenshots and/or additional information if needed.

**Comment by dnsmichi** [comment]
I'm not sure if proxypass really works with Dashing, never tested this. According to users at https://community.icinga.com it does - asking there is a better chance for replies than here.
