### ISSUE TITLE
sample dashbaord blank

### ISSUE THREAD

**Issue by webkida** [mocdaniel/dashing-icinga2#77]
I am trying to setup cool dashboard for my new icinga setup, below is the URL where I have it setup.
The default dashboard is not appealing enough so trying few new ones. The sample dashboard provided does not show any values in it, can anyone please help me over here.

**Comment by dnsmichi** [comment]
The `sample` dashboard is not supported nor implemented, solely use (and modify) `icinga2` for this project.
