### ISSUE TITLE
Service down number not matching

### ISSUE THREAD

**Issue by webkida** [mocdaniel/dashing-icinga2#79]
I have dashing installed and working properly. I just had few queries. How does the calculation of service or host down work. The numbers of All problem and the actual problem do not add up. Attached is the screenshot of my setup. Can someone please explain how it works.

https://imgur.com/a/L9DMeNe

**Comment by dnsmichi** [comment]
Numbers look ok to me, those are all unhandled problems. In case you want to learn more about the implementation, check the development docs: https://github.com/dnsmichi/dashing-icinga2#development

For other questions which are not bugs, please head over to https://community.icinga.com
