### ISSUE TITLE
Dual login windows/iFrames w/Ruby using RHSCL

### ISSUE THREAD

**Issue by fireheadman** [mocdaniel/dashing-icinga2#80]
Is there a preferred ruby version?
RHEL7 didn't have a high enough version, so had to enable RHSCL channel, but that has ruby 2.3, 2.4, 2.5, 2.6 to choose from.

EDIT: Seems to run fine on Ruby 2.6

**Comment by fireheadman** [comment]
UPDATE:   I was able to get this running using ruby2.6
disclaimer:  I am by no means a ruby expert, I'm winging it the best I can.

Using Redhat Software Collections (RHSCL) channel, things are a tad different.
By all means, if anyone has a better way to do this, please guide me.  I'm open ears!

I was unsuccessful in getting this to run without root (I did see the notice about not doing this as root)....
```
sudo su -
cd /usr/share/dashing-icinga2
source /opt/rh/rh-ruby26/enable
sudo scl enable rh-ruby26 'gem install bundler'
sudo scl enable rh-ruby26 'bundle'
```

```
cd /usr/share/dashing-icinga2/tools/systemd
sudo cp dashing-icinga2.service /usr/lib/systemd/system/
sudo vi /usr/lib/systemd/system/dashing-icinga2.service
```

Updated these lines for the service to stop/start/restart
```
ExecStart=/bin/bash -c '\
    source /opt/rh/rh-ruby26/enable ; \
    /opt/rh/rh-ruby26/root/usr/bin/dashing start -d -p 8005 --pid /var/run/thin.pid'
ExecStop=/opt/rh/rh-ruby26/root/usr/bin/dashing stop
```

Then daemon-reload followed by start.
Nav to http://<icingaserver>:8005   I see it... however I have 2 panel with 404 errors??

![image](https://user-images.githubusercontent.com/19847195/64578401-8129a780-d33c-11e9-9d17-9edb6d910903.png)


**Oh, I am also running the dashing service in foreground to view any errors... not seeing any.

**Comment by fireheadman** [comment]
Another UPDATE:
Edited the /usr/share/dashing-icinga2/config/icinga2.local.json file
changed the URL from "localhost" to the FQDN...

```
{
  "icinga2": {
    "api": {
      "host": "localhost",
      "port": 5665,
      "user": "dashing",
      "password": "dashing-password-here"
    }
  },
  "icingaweb2": {
    "url": "https://icinga01.example.com/icingaweb2"
  }
}
```


Also purposely messed up a host to make it throw a host issue"
Now I get this (2 login frames):

![image](https://user-images.githubusercontent.com/19847195/64579698-ff884880-d340-11e9-9bbc-64c2560a0258.png)

Also, this is the part that is confusing to me...
If I do not run as root:
```
[user@icinga01 dashing-icinga2 12183]$ scl enable rh-ruby26 'bundle'
Using backports 3.15.0
Following files may not be writable, so sudo is needed:
  /opt/rh/rh-ruby26/root/usr/bin
  /opt/rh/rh-ruby26/root/usr/share/gems
  /opt/rh/rh-ruby26/root/usr/share/gems/build_info
  /opt/rh/rh-ruby26/root/usr/share/gems/cache
  /opt/rh/rh-ruby26/root/usr/share/gems/doc
  /opt/rh/rh-ruby26/root/usr/share/gems/extensions
  /opt/rh/rh-ruby26/root/usr/share/gems/gems
  /opt/rh/rh-ruby26/root/usr/share/gems/specifications
```


And if I run as root:
```
[user@icingp01 dashing-icinga2 12186]$ sudo scl enable rh-ruby26 'bundle'
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on
this machine.
```

**Comment by fireheadman** [comment]
Oddly enough, If I provide my creds to those 2 login windows and refresh, it looks like it should.
Seems to be persistent after the first login.

Unsure what/why is causing this behavior.   I did see the post about X-Frames, that isn't even in my apache config, verified with curl -I output.

**Comment by dnsmichi** [comment]
I'm not sure why you would need Ruby from SCL. The Vagrant boxes use what's available in the base repo, and it works just fine.

**Comment by fireheadman** [comment]
I'll revisit this (using standard channel ruby) in a bit and report back.

**Comment by mocdaniel** [comment]
@fireheadman Were you able to resolve this issue or is it still persistent?

**Comment by fireheadman** [comment]
Have not reinstalled this package to test it

**Comment by mocdaniel** [comment]
I will then close this issue. iFrames seem to work with your configuration and the problem with installing the bundler gem via SCL has been documented as can be seen in #98
