### ISSUE TITLE
iFrame Title

### ISSUE THREAD

**Issue by pianogen** [mocdaniel/dashing-icinga2#82]
I want to add a title on top of the frame, like on all other widgets but it's not possible. How can I implement this?

**Comment by dnsmichi** [comment]
I'm not quite sure if I can follow ... can you create a mockup how it should look like?

**Comment by dnsmichi** [comment]
Haha, I see it how this works. Seems that the original iframe widget does nothing in regards of the coffee script but just use the browsers iframe capabilities.

I've modified the html widget, which broke the iframe update. But, luckily there's this gist: https://gist.github.com/hussfelt/a6fe71ebd7cce327df29

Combining this works ❤️ 
<img width="1181" alt="Screen Shot 2019-10-16 at 16 00 47" src="https://user-images.githubusercontent.com/382049/66926450-582cbe80-f02e-11e9-9135-5ca16506c724.png">

**Comment by pianogen** [comment]
Thank you very much for the change. :)

**Comment by pianogen** [comment]
I have a last question. 

Is possible to implement this change in version 2.0 too? 

We have at the moment only icinga 2.10 and cannot update atm.

**Comment by dnsmichi** [comment]
2.10 should work, I just raised the requirement to make people upgrade to 2.11 ;-) Try the Docker container then you're safe :)
