### ISSUE TITLE
Changing timezone

### ISSUE THREAD

**Issue by benhartwich** [mocdaniel/dashing-icinga2#92]
Hi,

how can I change the date / timezone of the dashlet? It seems that UTC is used by default although my server and icinga has the right timezone set.

**Comment by dnsmichi** [comment]
Edit this line: https://github.com/dnsmichi/dashing-icinga2/blob/master/dashboards/icinga2.erb#L17

**Comment by benhartwich** [comment]
Thanks, what´s the best practise when using docker environment?

**Comment by dnsmichi** [comment]
Rebuild the image and run it. Likewise, push it to your own registry. That applies for any changes made to the source code btw, also re-arranging dashlets.

**Comment by benhartwich** [comment]
Thanks. Hmm, I think an environment variable would be perfect - if it´s somehow possible. Or using the system´s date. It would be a little bit complicated staying updateable when I rebuild this image for my own, wouldn´t it?

**Comment by dnsmichi** [comment]
Sure, I just did not have time to look into a solution here. Likely you can create a similar one like #54 - feel free to create PR.

**Comment by dnsmichi** [comment]
You can test the linked PR.

```
michi@mbpmif ~/dev/github/dashing-icinga2 (feature/clock-timezone-config=) $ DASHBOARD_TIMEZONE="Europe/Berlin" binpaths/ruby/2.6.0/bin/smashing start -p 8005
```

![Screen Shot 2019-10-23 at 10 17 56](https://user-images.githubusercontent.com/382049/67372839-d59c8580-f57e-11e9-910b-01afe0ec671c.png)

**Comment by benhartwich** [comment]
Thank you very much - so the new environment variable will be DASHBOARD_TIMEZONE? Have I to build the docker manually or can I use docker pull?

**Comment by dnsmichi** [comment]
That's not in Docker atm, that's just a patch for the source code to try.
