### ISSUE TITLE
Wrong Data and Graphs Orientation on Mouse Over

### ISSUE THREAD

**Issue by aledr** [mocdaniel/dashing-icinga2#93]
Hi.

Using default dashboard with minimal configuration on config/icinga2.json displays wrong data and unexpected behavior on bars.
It changes orientation on mouse over and also display unknown/incorret information.

Check "Downtimes" on below image.

![image](https://user-images.githubusercontent.com/47945/67164663-6a22a000-f353-11e9-827b-2732b9a74549.png)

Check "Hosts" after mouse over on below image.

![image](https://user-images.githubusercontent.com/47945/67164678-9807e480-f353-11e9-9d79-eb6de15fb19d.png)

I can provide a public URL if you get in touch privately to show you the behaviours.

Thanks.

**Comment by dnsmichi** [comment]
Not sure what "wrong" data means, you did not provide a comparable number. The charts widgets for hosts and services only use problems (not in a downtime, not acknowledged) to actually count them. 

https://github.com/dnsmichi/dashing-icinga2/blob/master/jobs/icinga2.rb#L74
https://github.com/dnsmichi/dashing-icinga2/blob/master/lib/icinga2.rb#L752

The downtime chart looks modified in the first screenshot, what else did you modify in your environment? `git diff` for example. Also, please fill in the issue template for further details.

**Comment by aledr** [comment]
No modifications were done at all. git diff will only show the changes in "config/icinga2.json".
Hosts shows 1 Host Down on first image and It is correct, but shows 13 on the second image after mouse over.

**Comment by dnsmichi** [comment]
Ah. Seems chartjs is then using the default from the dashboard. https://github.com/dnsmichi/dashing-icinga2/blob/master/dashboards/icinga2.erb

I did not play with mouseover for chartjs, this was too complicated and I am not a JS developer either. These dashboards are typically used on TVs where no-one moves a mouse.

If you want to look into fixing this, the widget code & settings are located in https://github.com/dnsmichi/dashing-icinga2/blob/master/widgets/chartjs/chartjs.coffee#L45

**Comment by coderobe** [comment]
I am also running into this, this makes data evaluation rather useless. Couldn't mouseover just be disabled for the time being?

**Comment by dnsmichi** [comment]
If you tell me how, or send a PR, I'll gladly merge this :-)

**Comment by coderobe** [comment]
The pull request i sent does not fix the orientation issues due to a deeper issue with widget instantiation, but the wrong data should not show up anymore with #97 at least - which was the bigger issue of the two :p
